package main

import "github.com/openai/openai-go"

var tools = []openai.ChatCompletionToolParam{
	{
		Type: "function",
		Function: openai.FunctionDefinitionParam{
			Name:        "reset",
			Description: openai.String("Resets the interaction with the target LLM."),
			Parameters: openai.FunctionParameters{
				"type":       "object",
				"properties": map[string]interface{}{},
				"required":   []string{},
			},
		},
	},
	{
		Type: "function",
		Function: openai.FunctionDefinitionParam{
			Name:        "download",
			Description: openai.String("Downloads CSV and returns its contents."),
			Parameters: openai.FunctionParameters{
				"type":       "object",
				"properties": map[string]interface{}{},
				"required":   []string{},
			},
		},
	},
	{
		Type: "function",
		Function: openai.FunctionDefinitionParam{
			Name:        "prompt",
			Description: openai.String("Sends generated prompt to LLM."),
			Parameters: openai.FunctionParameters{
				"type": "object",
				"properties": map[string]interface{}{
					"prompt": map[string]string{
						"type":        "string",
						"description": "Clasification prompt generated by LLM do be sent to the target.",
					},
				},
				"required": []string{"prompt"},
			},
		},
	},
	{
		Type: "function",
		Function: openai.FunctionDefinitionParam{
			Name:        "success",
			Description: openai.String("To be called when flag is found."),
			Parameters: openai.FunctionParameters{
				"type": "object",
				"properties": map[string]interface{}{
					"flag": map[string]string{
						"type":        "string",
						"description": "The flag found.",
					},
				},
				"required": []string{"flag"},
			},
		},
	},
}
